/* global window */
// Sample data for Renewjen Academy

const SUBJECTS = [
  { id: "math",    ko: "수학",   en: "Mathematics" },
  { id: "korean",  ko: "국어",   en: "Korean Literature" },
  { id: "english", ko: "영어",   en: "English" },
  { id: "science", ko: "탐구",   en: "Science & Inquiry" },
  { id: "history", ko: "한국사", en: "Korean History" },
];

const INSTRUCTORS = [
  {
    id: "kim-jiwon",
    name: "김지원",
    nameEn: "Kim Ji-won",
    initials: "지원",
    subject: "수학",
    title: "수학 영역 · 미적분",
    bioShort: "서울대 수학과. 13년 차. 정통 풀이의 정석을 다시 쓰는 강사.",
    bio: "서울대학교 수학교육과를 졸업하고 13년간 수능 수학 강의를 진행해 왔습니다. 매년 만점자 80명 이상을 배출했으며, 풀이의 ‘이유’를 설명하는 강의로 정평이 나 있습니다.",
    students: 4820,
    rating: 4.9,
    courses: 6,
  },
  {
    id: "park-sera",
    name: "박세라",
    nameEn: "Park Se-ra",
    initials: "세라",
    subject: "국어",
    title: "국어 영역 · 문학·독서",
    bioShort: "고려대 국문과. 비문학 독해의 흐름을 다시 짜는 수업.",
    bio: "EBS 대표 국어 강사 출신. 비문학을 ‘읽는 방법’으로 가르치는 흐름 분석 수업으로 두터운 팬층을 보유하고 있습니다.",
    students: 6210,
    rating: 4.9,
    courses: 8,
  },
  {
    id: "lee-hyun",
    name: "이현우",
    nameEn: "Lee Hyun-woo",
    initials: "현우",
    subject: "영어",
    title: "영어 영역 · 구문·어휘",
    bioShort: "서울대 영문과. 영어를 구조로 해부하는 강의.",
    bio: "영어를 ‘문법’이 아니라 ‘구조’로 가르칩니다. 매주 1편의 원서 칼럼을 함께 읽는 라이브 클래스가 시그니처.",
    students: 3940,
    rating: 4.8,
    courses: 5,
  },
  {
    id: "jeong-min",
    name: "정민호",
    nameEn: "Jeong Min-ho",
    initials: "민호",
    subject: "탐구",
    title: "생명과학 I · II",
    bioShort: "KAIST 생명과학과. ‘왜 그런가’를 끝까지 묻는 수업.",
    bio: "KAIST 생명과학과 박사 수료. 단순 암기가 아니라 메커니즘을 따라가는 수업으로, 매년 1등급 비율이 가장 높은 강의입니다.",
    students: 2710,
    rating: 4.9,
    courses: 4,
  },
];

const COURSES = [
  {
    id: "math-calc-2026",
    no: "01",
    title: "2026 미적분 정수",
    subtitle: "Calculus, From First Principles",
    instructor: "kim-jiwon",
    subject: "math",
    level: "고3·N수",
    format: "라이브 + VOD",
    lessons: 48,
    hours: 96,
    weeks: 16,
    price: 580000,
    salePrice: 464000,
    rating: 4.9,
    reviews: 1284,
    enrolled: 2840,
    nextLive: "2026-05-22T20:00:00+09:00",
    classInRoomId: "RJ-2026-MATH-A1",
    color: "ink",
    badge: "BEST",
    description:
      "미적분 전 단원을 ‘왜 이렇게 푸는가’의 관점에서 재구성합니다. 매주 2회 라이브, 즉시 복습용 VOD 제공. 14주차 모의고사 풀이 라이브 포함.",
    syllabus: [
      { unit: "WEEK 01", title: "함수의 극한과 연속", lessons: 3, duration: "5h 40m" },
      { unit: "WEEK 02", title: "미분계수와 도함수", lessons: 3, duration: "5h 20m" },
      { unit: "WEEK 03", title: "여러 가지 함수의 미분", lessons: 3, duration: "6h 10m" },
      { unit: "WEEK 04", title: "도함수의 활용 I", lessons: 3, duration: "5h 55m" },
      { unit: "WEEK 05", title: "도함수의 활용 II", lessons: 3, duration: "6h 00m" },
      { unit: "WEEK 06", title: "부정적분과 정적분", lessons: 3, duration: "6h 20m" },
      { unit: "WEEK 07", title: "정적분의 활용", lessons: 3, duration: "5h 45m" },
      { unit: "WEEK 08", title: "중간 모의고사 풀이", lessons: 2, duration: "4h 00m" },
    ],
    includes: [
      "리뉴젠 라이브 수업 32회",
      "고화질 다시보기 VOD 무제한",
      "주간 첨삭 과제 14회",
      "전용 질문방 16주",
      "최종 모의고사 응시권 4회",
    ],
  },
  {
    id: "korean-lit-2026",
    no: "02",
    title: "문학·독서 정도",
    subtitle: "The Long Read",
    instructor: "park-sera",
    subject: "korean",
    level: "고2·고3",
    format: "라이브 + VOD",
    lessons: 56,
    hours: 112,
    weeks: 14,
    price: 520000,
    salePrice: 416000,
    rating: 4.9,
    reviews: 2104,
    enrolled: 3920,
    nextLive: "2026-05-21T19:00:00+09:00",
    classInRoomId: "RJ-2026-KOR-B2",
    color: "cream",
    badge: "신규",
    description: "비문학 독해는 ‘흐름’이다. 14주 동안 문장 단위가 아닌 단락의 호흡으로 읽는 법을 만듭니다.",
    syllabus: [
      { unit: "WEEK 01", title: "문장에서 단락으로", lessons: 4, duration: "6h 00m" },
      { unit: "WEEK 02", title: "주제어와 흐름 어휘", lessons: 4, duration: "6h 20m" },
      { unit: "WEEK 03", title: "철학·인문 지문", lessons: 4, duration: "6h 30m" },
      { unit: "WEEK 04", title: "과학·기술 지문", lessons: 4, duration: "6h 10m" },
      { unit: "WEEK 05", title: "사회·경제 지문", lessons: 4, duration: "6h 25m" },
      { unit: "WEEK 06", title: "문학 — 시", lessons: 4, duration: "5h 50m" },
      { unit: "WEEK 07", title: "문학 — 소설·수필", lessons: 4, duration: "6h 00m" },
    ],
    includes: [
      "리뉴젠 라이브 수업 28회",
      "지문 분석 PDF 56편",
      "주간 글쓰기 첨삭 14회",
      "교재 1권 (배송 포함)",
    ],
  },
  {
    id: "english-struct-2026",
    no: "03",
    title: "구문독해 RE:BUILD",
    subtitle: "Sentences, Restructured",
    instructor: "lee-hyun",
    subject: "english",
    level: "고1·고2",
    format: "라이브 + VOD",
    lessons: 40,
    hours: 80,
    weeks: 12,
    price: 460000,
    salePrice: 368000,
    rating: 4.8,
    reviews: 942,
    enrolled: 1810,
    nextLive: "2026-05-22T21:00:00+09:00",
    classInRoomId: "RJ-2026-ENG-C1",
    color: "accent",
    description: "수능 영어를 ‘구조’의 언어로 다시 봅니다. 매주 원서 칼럼 한 편을 라이브로 함께 분석합니다.",
    syllabus: [
      { unit: "WEEK 01", title: "구조의 원자 — 5형식 재정의", lessons: 3, duration: "5h 00m" },
      { unit: "WEEK 02", title: "관계사의 진짜 역할", lessons: 3, duration: "4h 50m" },
      { unit: "WEEK 03", title: "분사와 분사구문", lessons: 3, duration: "5h 10m" },
      { unit: "WEEK 04", title: "도치·강조 구문", lessons: 3, duration: "4h 40m" },
    ],
    includes: ["리뉴젠 라이브 수업 24회", "원서 칼럼 12편", "어휘 노트 PDF"],
  },
  {
    id: "bio-iiv-2026",
    no: "04",
    title: "생명과학 메커니즘",
    subtitle: "Mechanism Over Memory",
    instructor: "jeong-min",
    subject: "science",
    level: "고3·N수",
    format: "라이브 + VOD",
    lessons: 44,
    hours: 88,
    weeks: 14,
    price: 540000,
    salePrice: 432000,
    rating: 4.9,
    reviews: 720,
    enrolled: 1340,
    nextLive: "2026-05-23T20:00:00+09:00",
    classInRoomId: "RJ-2026-SCI-D1",
    color: "deep",
    description: "생명과학을 외우지 않습니다. 메커니즘을 따라가면 보기가 풀립니다.",
    syllabus: [
      { unit: "WEEK 01", title: "세포와 물질 출입", lessons: 4, duration: "6h" },
      { unit: "WEEK 02", title: "유전자의 발현", lessons: 4, duration: "6h 30m" },
      { unit: "WEEK 03", title: "신경계의 흥분 전도", lessons: 4, duration: "6h 20m" },
    ],
    includes: ["리뉴젠 라이브 수업 22회", "메커니즘 도해집", "유전 계산 워크북"],
  },
  {
    id: "korean-history-2026",
    no: "05",
    title: "한국사 한 학기",
    subtitle: "One Semester, Whole History",
    instructor: "park-sera",
    subject: "history",
    level: "고1~고3",
    format: "VOD",
    lessons: 32,
    hours: 48,
    weeks: 10,
    price: 280000,
    salePrice: 224000,
    rating: 4.7,
    reviews: 510,
    enrolled: 980,
    color: "cream",
    description: "한 학기에 끝내는 한국사. 모의고사·내신 둘 다 잡는 32강 구성.",
    syllabus: [{ unit: "WEEK 01", title: "선사 ~ 삼국", lessons: 3, duration: "4h 30m" }],
    includes: ["VOD 32강", "연표 PDF", "기출 200제"],
  },
  {
    id: "math-prob-2026",
    no: "06",
    title: "확률과 통계 완성",
    subtitle: "Probability, End to End",
    instructor: "kim-jiwon",
    subject: "math",
    level: "고3·N수",
    format: "라이브 + VOD",
    lessons: 36,
    hours: 72,
    weeks: 12,
    price: 480000,
    salePrice: 384000,
    rating: 4.8,
    reviews: 612,
    enrolled: 1620,
    color: "ink",
    description: "선택과목의 점수를 결정짓는 12주.",
    syllabus: [{ unit: "WEEK 01", title: "경우의 수 재정의", lessons: 3, duration: "5h" }],
    includes: ["리뉴젠 라이브 18회", "기출 분류집"],
  },
];

const REVIEWS = [
  {
    id: "r1",
    courseId: "math-calc-2026",
    name: "이*수",
    grade: "고3",
    rating: 5,
    date: "2026.04.18",
    body: "‘왜 이렇게 푸는지’가 처음으로 이해됐어요. 풀이를 외우던 시절로 돌아가고 싶지 않습니다.",
  },
  {
    id: "r2",
    courseId: "math-calc-2026",
    name: "박*연",
    grade: "N수생",
    rating: 5,
    date: "2026.03.27",
    body: "라이브 수업 후 즉시 복습이 가능한 게 가장 큰 장점. 강의실 안에서 질문도 바로 받아주시고.",
  },
  {
    id: "r3",
    courseId: "korean-lit-2026",
    name: "정*은",
    grade: "고2",
    rating: 5,
    date: "2026.04.02",
    body: "비문학에 ‘방법’이 있다는 걸 처음 알았습니다. 14주 만에 등급이 두 칸 올랐어요.",
  },
];

const NOTICES = [
  { id: "n1", category: "공지", title: "2026 여름 라이브 시즌 시간표 공개", date: "2026.05.18", pinned: true },
  { id: "n2", category: "공지", title: "라이브 강의실 데스크탑 앱 업데이트 안내", date: "2026.05.14", pinned: true },
  { id: "n3", category: "이벤트", title: "신규 수강생 첫 주 환급 캠페인", date: "2026.05.10", pinned: false },
  { id: "n4", category: "안내", title: "장학생 선발 결과 발표 (5월)", date: "2026.05.07", pinned: false },
  { id: "n5", category: "공지", title: "다시보기 다운로드 기능 종료 안내", date: "2026.04.28", pinned: false },
  { id: "n6", category: "안내", title: "여름방학 특강 사전 신청 오픈", date: "2026.04.21", pinned: false },
];

// User account that "exists" — login simulation
const ACCOUNT = {
  email: "student@renewjen.kr",
  password: "renewjen", // demo only
  name: "한도윤",
  initials: "도윤",
  grade: "고2",
  enrolled: ["korean-lit-2026", "english-struct-2026"], // already owns
  watchHistory: {
    "korean-lit-2026": { lessonIdx: 6, progressPct: 42, lastWatchedAt: "2026.05.19 22:14" },
    "english-struct-2026": { lessonIdx: 2, progressPct: 18, lastWatchedAt: "2026.05.18 20:01" },
  },
};

Object.assign(window, {
  SUBJECTS, INSTRUCTORS, COURSES, REVIEWS, NOTICES, ACCOUNT,
});
